spring.application.name=demo

spring.jpa.generate-ddl=true


spring.datasource.url=jdbc:postgresql://localhost:5432/nns-one
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/api/user/login

##JWT##
jwt.duration=30
jwt.algorithm=HmacSHA256
jwt.zone=America/Mexico_City
jwt.secret=kptf+JsEDQ0pC9fyAYKV2DWAKrrRVM6vB44vyDBXFrY=