spring.application.name=demo

spring.jpa.generate-ddl=false


spring.datasource.url=jdbc:postgresql://localhost:5432/nns-one
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver